CREATE TABLE event_airports
(
    event_id BIGINT NOT NULL,
    icao     VARCHAR(255)
);

CREATE TABLE events
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    vatsim_id   BIGINT                                  NOT NULL,
    name        VARCHAR(255)                            NOT NULL,
    description TEXT,
    banner_url  VARCHAR(255),
    start_time  TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    end_time    TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    link        VARCHAR(255),
    CONSTRAINT pk_events PRIMARY KEY (id)
);

ALTER TABLE bookings
    ADD event_id BIGINT;

ALTER TABLE bookings
    ADD position VARCHAR(20);

ALTER TABLE bookings
    ALTER COLUMN event_id SET NOT NULL;

ALTER TABLE bookings
    ALTER COLUMN position SET NOT NULL;

ALTER TABLE events
    ADD CONSTRAINT uc_events_vatsim UNIQUE (vatsim_id);

ALTER TABLE bookings
    ADD CONSTRAINT FK_BOOKINGS_ON_EVENT FOREIGN KEY (event_id) REFERENCES events (id);

ALTER TABLE event_airports
    ADD CONSTRAINT fk_event_airports_on_event FOREIGN KEY (event_id) REFERENCES events (id);